#%RAML 1.0 NamedExample
[
  {
    "oid": "1531o31kzpp",
    "account-id": "BoiBL",
    "items": [
    {
      "id": "HwQI4s",
      "sku": "LgbNe",
      "unit-price": 347273.9365793999,
      "quantity": 910587,
      "final-price": -514697.5385577277,
      "taxable": true
    },
    {
    "id": "8jvvb",
    "sku": "98G00",
    "unit-price": 500153.0051596072,
    "quantity": 377260,
    "final-price": 803171.8918841204,
    "taxable": false
    }
    ],
  "order-date": 2016-02-28T16:41:41.090Z,
  "status": "ER5W0",
  "total-tax": 509092.0478337166
  },
  {
    "oid": "3456o31kzpp",
    "account-id": "BkgBL",
    "items": [
    {
      "id": "HwQI4s",
      "sku": "LgbNe",
      "unit-price": 347273.9365793999,
      "quantity": 910587,
      "final-price": -514697.5385577277,
      "taxable": true
    },
    {
    "id": "8jvvb",
    "sku": "98G00",
    "unit-price": 500153.0051596072,
    "quantity": 377260,
    "final-price": 803171.8918841204,
    "taxable": false
    }
    ],
  "order-date": 2016-02-28T16:41:41.090Z,
  "status": "ER5W0",
  "total-tax": 509092.0478337166
  }
]